version: '3'

env:
  NODE_ENV: '{{default "development" .NODE_ENV}}'

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  # Service Management Tasks
  check:
    desc: Check prerequisites for running services
    cmds:
      - bash scripts/check-prerequisites.sh

  start:
    desc: Start all services (PostgreSQL, Redis, ChromaDB)
    cmds:
      - bash scripts/start-services.sh

  stop:
    desc: Stop all services gracefully
    cmds:
      - bash scripts/stop-services.sh

  restart:
    desc: Restart all services
    cmds:
      - task: stop
      - task: start

  status:
    desc: Show status of all services
    cmds:
      - podman ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}" | grep aeonisk || echo "No Aeonisk services running"

  logs:
    desc: Show logs from all services
    cmds:
      - podman compose logs -f

  diagnose:
    desc: Diagnose connection issues
    cmds:
      - bash scripts/diagnose-connections.sh

  # Database Tasks
  db:init:
    desc: Initialize databases
    cmds:
      - bash scripts/init-databases.sh

  db:psql:
    desc: Connect to PostgreSQL interactive shell
    cmds:
      - podman exec -it aeonisk-postgres psql -U aeonisk -d aeonisk_game

  db:redis:
    desc: Connect to Redis CLI
    cmds:
      - podman exec -it aeonisk-redis redis-cli

  # Development Tasks
  install:
    desc: Install dependencies
    cmds:
      - npm install

  dev:
    desc: Run development server with hot reload
    cmds:
      - npm run dev

  test:
    desc: Run tests
    cmds:
      - npm test

  test:watch:
    desc: Run tests in watch mode
    cmds:
      - npm run test:watch

  test:coverage:
    desc: Run tests with coverage
    cmds:
      - npm run test:coverage

  build:
    desc: Build the project
    cmds:
      - npm run build

  # Cleanup Tasks
  clean:
    desc: Stop services and remove containers (keeps data)
    cmds:
      - podman compose down

  clean:all:
    desc: Stop services and remove everything including volumes (DESTRUCTIVE)
    cmds:
      - podman compose down -v
    prompt: This will delete all data. Are you sure?

  # Utility Tasks
  lint:
    desc: Run linter
    cmds:
      - npm run lint

  typecheck:
    desc: Run type checking
    cmds:
      - npm run typecheck