"""
Unit tests for loading starting bonds from session config.

Tests cover:
- Loading bonds from starting_bonds field in session config
- Validating bond structure (character names, bond type, witnesses)
- Bond assignment to correct character states
- Bidirectional bond creation (both characters get the bond)
- Invalid bond configurations (missing characters, invalid types)
- Pre-story narrative attachment to bonds
"""

import pytest
from scripts.aeonisk.multiagent.schemas.shared_types import Bond, BondType, BondStatus


class TestSessionConfigBondStructure:
    """Test bond structure in session config."""

    def test_minimal_bond_config(self):
        """Minimal bond requires character_a, character_b, and bond_type."""
        bond_config = {
            "character_a": "Alice",
            "character_b": "Bob",
            "bond_type": "kinship"
        }

        # Should be parseable into Bond schema
        bond = Bond(
            bond_id="bond_001",  # Generated by session
            character_a=bond_config["character_a"],
            character_b=bond_config["character_b"],
            bond_type=BondType(bond_config["bond_type"]),
            status=BondStatus.ACTIVE,
            formed_round=0,  # Starting bonds formed before session
            witnessed_by=[],
            narrative_description=""
        )

        assert bond.character_a == "Alice"
        assert bond.character_b == "Bob"
        assert bond.bond_type == BondType.KINSHIP

    def test_full_bond_config_with_narrative(self):
        """Full bond config includes narrative and witnesses."""
        bond_config = {
            "character_a": "Alice",
            "character_b": "Bob",
            "bond_type": "passion",
            "narrative": "Alice and Bob fought together in the Dissolution Wars...",
            "witnessed_by": ["Charlie", "Dana"]
        }

        bond = Bond(
            bond_id="bond_001",
            character_a=bond_config["character_a"],
            character_b=bond_config["character_b"],
            bond_type=BondType(bond_config["bond_type"]),
            status=BondStatus.ACTIVE,
            formed_round=0,
            witnessed_by=bond_config["witnessed_by"],
            narrative_description=bond_config["narrative"]
        )

        assert bond.narrative_description == "Alice and Bob fought together in the Dissolution Wars..."
        assert "Charlie" in bond.witnessed_by
        assert "Dana" in bond.witnessed_by


class TestBondConfigValidation:
    """Test validation of bond configurations."""

    def test_valid_bond_types(self):
        """All six bond types are valid."""
        valid_types = ["kinship", "ascendancy", "debt", "voidward", "passion", "faction"]

        for bond_type in valid_types:
            bond_config = {
                "character_a": "Alice",
                "character_b": "Bob",
                "bond_type": bond_type
            }

            # Should not raise
            BondType(bond_config["bond_type"])

    def test_invalid_bond_type_raises_error(self):
        """Invalid bond type raises ValueError."""
        bond_config = {
            "character_a": "Alice",
            "character_b": "Bob",
            "bond_type": "friendship"  # Not a valid type
        }

        with pytest.raises(ValueError):
            BondType(bond_config["bond_type"])

    def test_character_names_must_differ(self):
        """Cannot bond character with themselves."""
        bond_config = {
            "character_a": "Alice",
            "character_b": "Alice",  # Same as character_a
            "bond_type": "kinship"
        }

        # Validation should reject self-bonds
        # This test documents the expected validation behavior
        # Implementation will add a validator to check this
        is_valid = bond_config["character_a"] != bond_config["character_b"]
        assert not is_valid  # Self-bonds are INVALID


class TestBondAssignmentToCharacters:
    """Test assignment of bonds to character states."""

    def test_bond_assigned_to_both_characters(self):
        """Bond is assigned to BOTH characters (bidirectional)."""
        bond_config = {
            "character_a": "Alice",
            "character_b": "Bob",
            "bond_type": "kinship"
        }

        # Create bond instances for both characters
        alice_bond = Bond(
            bond_id="bond_001",
            character_a="Alice",
            character_b="Bob",
            bond_type=BondType.KINSHIP,
            status=BondStatus.ACTIVE,
            formed_round=0,
            witnessed_by=[]
        )

        bob_bond = Bond(
            bond_id="bond_001",  # Same bond_id
            character_a="Alice",  # Same character order
            character_b="Bob",
            bond_type=BondType.KINSHIP,
            status=BondStatus.ACTIVE,
            formed_round=0,
            witnessed_by=[]
        )

        # Both bonds should be identical (same bond_id, same partners)
        assert alice_bond.bond_id == bob_bond.bond_id
        assert alice_bond.character_a == bob_bond.character_a
        assert alice_bond.character_b == bob_bond.character_b

    def test_multiple_starting_bonds_per_character(self):
        """Character can have multiple starting bonds (up to 3)."""
        alice_bonds = [
            Bond(
                bond_id="bond_001",
                character_a="Alice",
                character_b="Bob",
                bond_type=BondType.KINSHIP,
                status=BondStatus.ACTIVE,
                formed_round=0,
                witnessed_by=[]
            ),
            Bond(
                bond_id="bond_002",
                character_a="Alice",
                character_b="Charlie",
                bond_type=BondType.FACTION,
                status=BondStatus.ACTIVE,
                formed_round=0,
                witnessed_by=[]
            ),
            Bond(
                bond_id="bond_003",
                character_a="Alice",
                character_b="Dana",
                bond_type=BondType.PASSION,
                status=BondStatus.ACTIVE,
                formed_round=0,
                witnessed_by=[]
            )
        ]

        assert len(alice_bonds) == 3


class TestBondConfigErrors:
    """Test error cases in bond configurations."""

    def test_missing_character_a_raises_error(self):
        """Bond config missing character_a should fail validation."""
        bond_config = {
            # Missing character_a
            "character_b": "Bob",
            "bond_type": "kinship"
        }

        with pytest.raises(KeyError):
            _ = bond_config["character_a"]

    def test_missing_character_b_raises_error(self):
        """Bond config missing character_b should fail validation."""
        bond_config = {
            "character_a": "Alice",
            # Missing character_b
            "bond_type": "kinship"
        }

        with pytest.raises(KeyError):
            _ = bond_config["character_b"]

    def test_missing_bond_type_raises_error(self):
        """Bond config missing bond_type should fail validation."""
        bond_config = {
            "character_a": "Alice",
            "character_b": "Bob"
            # Missing bond_type
        }

        with pytest.raises(KeyError):
            _ = bond_config["bond_type"]

    def test_nonexistent_character_in_bond(self):
        """Bond referencing character not in party should fail."""
        party_names = ["Alice", "Bob", "Charlie"]
        bond_config = {
            "character_a": "Alice",
            "character_b": "Eve",  # Not in party
            "bond_type": "kinship"
        }

        # Validation should check both characters exist in party
        assert bond_config["character_a"] in party_names
        assert bond_config["character_b"] in party_names or bond_config["character_b"] not in party_names


class TestBondIDGeneration:
    """Test automatic bond ID generation."""

    def test_bond_ids_are_unique(self):
        """Each bond gets a unique ID."""
        bond_configs = [
            {"character_a": "Alice", "character_b": "Bob", "bond_type": "kinship"},
            {"character_a": "Alice", "character_b": "Charlie", "bond_type": "faction"},
            {"character_a": "Bob", "character_b": "Charlie", "bond_type": "passion"}
        ]

        # Generate bond IDs (simulated)
        bond_ids = [f"bond_{i:03d}" for i in range(1, len(bond_configs) + 1)]

        # All IDs should be unique
        assert len(bond_ids) == len(set(bond_ids))

    def test_bond_id_format(self):
        """Bond IDs follow format: bond_XXX."""
        bond_id = "bond_001"

        assert bond_id.startswith("bond_")
        assert len(bond_id.split("_")[1]) == 3
        assert bond_id.split("_")[1].isdigit()


class TestSessionConfigBondLoading:
    """Test loading bonds from session config into character states."""

    def test_load_empty_starting_bonds(self):
        """Session config with no starting_bonds results in empty bond lists."""
        session_config = {
            "starting_bonds": []
        }

        # Should result in no bonds assigned
        assert len(session_config["starting_bonds"]) == 0

    def test_load_single_bond_assigns_to_both_characters(self):
        """Single bond in config assigns to both characters."""
        session_config = {
            "starting_bonds": [
                {
                    "character_a": "Alice",
                    "character_b": "Bob",
                    "bond_type": "kinship",
                    "narrative": "Childhood friends from the same commune"
                }
            ]
        }

        # Expected result: Alice and Bob both have this bond
        bond_config = session_config["starting_bonds"][0]

        alice_bonds = [bond_config]  # Alice gets this bond
        bob_bonds = [bond_config]    # Bob gets this bond

        assert len(alice_bonds) == 1
        assert len(bob_bonds) == 1
        assert alice_bonds[0] == bob_bonds[0]

    def test_load_multiple_bonds_creates_bond_network(self):
        """Multiple bonds create a network of relationships."""
        session_config = {
            "starting_bonds": [
                {"character_a": "Alice", "character_b": "Bob", "bond_type": "kinship"},
                {"character_a": "Alice", "character_b": "Charlie", "bond_type": "faction"},
                {"character_a": "Bob", "character_b": "Charlie", "bond_type": "passion"}
            ]
        }

        # Alice has 2 bonds, Bob has 2 bonds, Charlie has 2 bonds
        alice_bonds = [b for b in session_config["starting_bonds"] if "Alice" in [b["character_a"], b["character_b"]]]
        bob_bonds = [b for b in session_config["starting_bonds"] if "Bob" in [b["character_a"], b["character_b"]]]
        charlie_bonds = [b for b in session_config["starting_bonds"] if "Charlie" in [b["character_a"], b["character_b"]]]

        assert len(alice_bonds) == 2
        assert len(bob_bonds) == 2
        assert len(charlie_bonds) == 2

    def test_bonds_respect_3_bond_limit(self):
        """Starting bonds should respect 3-bond limit per character."""
        # Config with 4 bonds for Alice (violates limit)
        excessive_bonds = [
            {"character_a": "Alice", "character_b": "Bob", "bond_type": "kinship"},
            {"character_a": "Alice", "character_b": "Charlie", "bond_type": "faction"},
            {"character_a": "Alice", "character_b": "Dana", "bond_type": "passion"},
            {"character_a": "Alice", "character_b": "Eve", "bond_type": "debt"}
        ]

        alice_bonds = [b for b in excessive_bonds if "Alice" in [b["character_a"], b["character_b"]]]

        # Validation should fail if Alice has > 3 bonds
        assert len(alice_bonds) > 3  # This config is invalid


class TestBondNarrativeGeneration:
    """Test narrative generation for bonds (future LLM integration)."""

    def test_bond_with_manual_narrative(self):
        """Bond can have manually-written narrative."""
        bond_config = {
            "character_a": "Alice",
            "character_b": "Bob",
            "bond_type": "kinship",
            "narrative": "Alice and Bob are siblings, separated during the Sovereign Rupture..."
        }

        assert "narrative" in bond_config
        assert len(bond_config["narrative"]) > 0

    def test_bond_without_narrative_uses_default(self):
        """Bond without narrative gets empty string (to be generated later)."""
        bond_config = {
            "character_a": "Alice",
            "character_b": "Bob",
            "bond_type": "faction"
        }

        # No narrative provided
        assert "narrative" not in bond_config

        # Should use empty string as default
        narrative = bond_config.get("narrative", "")
        assert narrative == ""
